# Generated by Django 3.0.3 on 2020-02-21 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='amount_booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('deleted_at', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='countries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shortcode', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=40)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('deleted_at', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_numer', models.CharField(max_length=200)),
                ('floor', models.IntegerField()),
                ('description', models.TextField()),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('deleted_at', models.TimeField(auto_now_add=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.categories')),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('deleted_at', models.TimeField(auto_now_add=True)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.countries')),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_from', models.DateTimeField(auto_now_add=True)),
                ('time_to', models.DateTimeField(auto_now_add=True)),
                ('additional_information', models.TextField()),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('deleted_at', models.TimeField(auto_now_add=True)),
                ('amount_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.amount_booking')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.customer')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.room')),
            ],
        ),
    ]
